# Generated by Django 6.0.1 on 2026-06-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
